# Generated by Django 3.1.5 on 2021-01-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('followings', models.ManyToManyField(related_name='_user_followings_+', to='user.User')),
                ('like_posts', models.ManyToManyField(related_name='like_users', to='post.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
