# Generated by Django 3.1.5 on 2021-02-22 10:49

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=post.models.user_upload_to),
        ),
    ]
